### ISSUE TITLE
Would be nice to retrieve networks for NatService 

### ISSUE THREAD

**Issue by annashipman** [gds-operations/vcloud-edge_gateway#106]
We specify networks by id.

The reason for specifying by ID are:

* network names are not necessarily unique (the 'shared from another vDC' problem)
* uplink networks (connected to an external provider network) are not available via the Query API.

We could potentially do some magic on the value of the network: field in the YAML, to make things easier for the user.

eg: 

* 'uplink' => use the uplink network, if there is only one.
* {name} => use the named network, if it is unique (error if not)
* {uuid} => to be safe, specify the network by its unique uuid.

**Comment by deanwilson** [comment]
Thank you for your interest in this project but we now consider it
both feature complete for our own usage and in maintenance mode.
While we will not be investing any more development time in this
project we may still include pull requests.
