### ISSUE TITLE
Allow specification of IP prefix arrays for firewall rules

### ISSUE THREAD

**Issue by annashipman** [gds-operations/vcloud-edge_gateway#107]
So that we do not need to repeat config sections for rules that apply to many prefixes (e.g. Fastly).

The diff only needs to show expanded IPs, not grouped.

**Comment by deanwilson** [comment]
Thank you for your interest in this project but we now consider it
both feature complete for our own usage and in maintenance mode.
While we will not be investing any more development time in this
project we may still include pull requests.
