### ISSUE TITLE
Specifying an abritrary string for a pool's service port protocol does not fail schema validation

### ISSUE THREAD

**Issue by annashipman** [gds-operations/vcloud-edge_gateway#108]
I can set [the protocol](https://github.com/alphagov/vcloud-edge_gateway/blob/e0c3685fc51b8b52de4871c7d314b86fe640c212/spec/vcloud/edge_gateway/configuration_generator/data/load_balancer_https-input.yaml#L11) for a load balancer pool service port to any arbitrary string (e.g. 'Anna') and no validation error is raised.

We don't check for this setting in [the schema validation](https://github.com/gds-operations/vcloud-edge_gateway/blob/e0c3685fc51b8b52de4871c7d314b86fe640c212/lib/vcloud/edge_gateway/schema/load_balancer_service.rb#L36-L40), nor do we raise an error if something exists in the configuration but not in our schema.

**Comment by deanwilson** [comment]
Thank you for your interest in this project but we now consider it
both feature complete for our own usage and in maintenance mode.
While we will not be investing any more development time in this
project we may still include pull requests.
