### ISSUE TITLE
Allow load balancer members to set a different port to default

### ISSUE THREAD

**Issue by annashipman** [gds-operations/vcloud-edge_gateway#112]
The API documentations says "Each Member of a load balancer Pool can contain its own ServicePort element. If this element is present in a Member, its contents override the ServicePort element of the Pool."

We do not support this (though [our schema](https://github.com/gds-operations/vcloud-edge_gateway/blob/e0c3685fc51b8b52de4871c7d314b86fe640c212/lib/vcloud/edge_gateway/schema/load_balancer_service.rb#L9) makes it look like we do.

We should.

**Comment by deanwilson** [comment]
Thank you for your interest in this project but we now consider it
both feature complete for our own usage and in maintenance mode.
While we will not be investing any more development time in this
project we may still include pull requests.
