### ISSUE TITLE
NAT rules do not support descriptions

### ISSUE THREAD

**Issue by samjsharpe** [gds-operations/vcloud-edge_gateway#126]
- According to the VCloud API documentation, the [Description attribute is supported](http://pubs.vmware.com/vcd-51/topic/com.vmware.vcloud.api.reference.doc_51/doc/types/NatRuleType.html)
- The Schema in [`vcloud::edge_gateway::nat_service`](https://github.com/gds-operations/vcloud-edge_gateway/blob/master/lib/vcloud/edge_gateway/schema/nat_service.rb) already supports this attribute,
- When [the configuration generator collects the NAT rules](https://github.com/gds-operations/vcloud-edge_gateway/blob/master/lib/vcloud/edge_gateway/configuration_generator/nat_service.rb#L23-L31
), it does not do anything with the description.

Fixing this problem _may_ be as simple as adding `new_rule[:Description] = rule[:description] if rule.key?(:description)` around line 27 of [`configuration_generator/nat_service.rb`](https://github.com/gds-operations/vcloud-edge_gateway/blob/master/lib/vcloud/edge_gateway/configuration_generator/nat_service.rb#L27) and adding appropriate tests.

**Comment by surminus** [comment]
This was added in https://github.com/gds-operations/vcloud-edge_gateway/pull/145
