### ISSUE TITLE
No documentation of static_routing_service

### ISSUE THREAD

**Issue by JamesBelchamber** [gds-operations/vcloud-edge_gateway#132]
There is nothing in the readme suggesting this exists, even though it was added in #123 - though there is a helpful example :)

**Comment by mattbostock** [comment]
Thanks for raising this @JamesBelchamber, would you like to raise a pull request to document this in the README?

**Comment by JamesBelchamber** [comment]
I haven't got the time or the knowledge, which is why I raised it as an issue :) I might be able to provide something at some point (we are planning on using this feature), but that shouldn't stop anyone else from attempting to if they have the time and the knowledge (and the inclination)..

**Comment by surminus** [comment]
Hi @JamesBelchamber,

I've updated the documentation to reflect a couple of extra features that have been added as per https://github.com/gds-operations/vcloud-edge_gateway/commit/3de509cca8e699df546cc20bc221da14446b826c

Thanks again for raising this :) 

Cheers,
Paul
