### ISSUE TITLE
Allow firewall rules to use Mustache file includes

### ISSUE THREAD

**Issue by alexmuller** [gds-operations/vcloud-edge_gateway#141]
Mustache provides the concept of including partials:

``` mustache
base.mustache:
<h2>Names</h2>
{{#names}}
  {{> user}}
{{/names}}

user.mustache:
<strong>{{name}}</strong>
```

We have a lot of firewall rules so it would be useful to be able to include them from other files to keep things easy to read and change.

It looks like this would require changes to `vcloud-core`, specifically `Vcloud::Core::ConfigLoader.load_config`.

**Comment by deanwilson** [comment]
Thank you for your interest in this project but we now consider it
both feature complete for our own usage and in maintenance mode.
While we will not be investing any more development time in this
project we may still include pull requests.
