### ISSUE TITLE
Increase timeout for deployment

### ISSUE THREAD

**Issue by surminus** [gds-operations/vcloud-edge_gateway#150]
Recording here so I don't forget. 

The current default timeout is 10 minutes. In some cases, a vendor may take longer than 10 minutes to deploy the rules. vcloud-edge_gateway will throw an error, but the rules will still eventually be applied. 

We should be able to specify the timeout amount.

**Comment by deanwilson** [comment]
This tool is no longer in active use and the repository will be archived so we're closing this pull request. Thank you for your interest and involvement in this project.
