### ISSUE TITLE
static-route support

### ISSUE THREAD

**Issue by abridgett** [gds-operations/vcloud-edge_gateway#93]
It'd be great to add static route support (we use nat and firewall settings currently then have to suffer the humiliation of manually setting static routes!)  Thanks

**Comment by alexmuller** [comment]
I think #121 is related to this issue.

**Comment by mattbostock** [comment]
This functionality is included in [version 1.5.0](https://rubygems.org/gems/vcloud-edge_gateway/versions/1.5.0).

You can see an example configuration here: [`/examples/vcloud-configure-edge/static-routing-rules.yaml`](https://github.com/gds-operations/vcloud-edge_gateway/blob/474fade471f96cd768c1483c17748cc2bf4118c6/examples/vcloud-configure-edge/static-routing-rules.yaml)

**Comment by abridgett** [comment]
Terrific, thanks Matt!
